export const INCOME_TYPES ={
  GET_INCOMES:'GET_INCOMES',
  CREATE_INCOME:'CREATE_INCOME',
  DELETE_INCOME:'DELETE_INCOME',
  
}

export const EXPENSES_TYPE ={
  GET_EXPENSES:'GET_EXPENSES',
  CREATE_EXPENSE:'CREATE_EXPENSE',
  DELETE_EXPENSE:'DELETE_EXPENSE',
}

export const AUTH_TYPE = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_SIGNIN: "USER_SIGNIN",
  // USER_LOGOUT:"USER_LOGOUT"
};
